### ISSUE TITLE
mysql select users

### ISSUE THREAD

**Issue by adriben** [go-gywn/query-exporter#1]
Is it possible to pass a query in the metrics to check the number of users from a database? Let's say I have a database called test and a table called users. My I know what kind of query should I write in the config-metrics? Sorry if it is a stupid question, I am new to prometheus

**Comment by gywndi** [comment]
Hi

I think, this could be helpful for your case.
```yaml
metric01:
  targets: ["dev"]
  collects:
  - query: "select user, 
                   substring_index(host, ':', 1) host,
                   db,
                   count(*) sessions
            from information_schema.processlist
            group by 1,2,3"
    timeout: 2
    metrics:
      process_count:
        type: gauge
        description: Session count
        labels: ["user","host", "db"]
        value: "sessions"
```

You can change query and labels, if you want collect only user count, as below.
```yaml
metric01:
  targets: ["dev"]
  collects:
  - query: "select user, count(*) sessions from information_schema.processlist group by 1"
    timeout: 2
    metrics:
      process_count:
        type: gauge
        description: Session count
        labels: ["user"]
        value: "sessions"
```

Best regards,
Chan.
